policy_ordering_test:
  run_dir: /home/obola/repositories/cicero-scm-surrogate/data/20250930_223742/marl_results/paper_accuracy_20251006_152956_20251002_081632_gru_128_1_homogenous_agents/policy_consistency_check/20251006_183002_1000
  gamma: 0.999