policy_consistency_test:
  run_dir: /home/obola/repositories/cicero-scm-surrogate/data/20250930_223742/marl_results/paper_accuracy_hetero_20251007_085957_20251006_125016_tcn_128_5_heterogenous_agents
  n_samples: 1000
  random_seed: 42