general:
  data_id: /home/obola/repositories/cicero-scm-surrogate/data/20250930_223742
  device: cuda
model:
  model_type: gru
  hidden_dims: 128
  num_layers: 1
  lr: 0.001
  weight_decay: 0.0001
  epochs: 250
  batch_size: 512
  num_workers: 2
  early_stopping: 30
scheduler:
  factor: 0.5
  patience: 5
  min_lr: 0.000001
